application:
  title: @project.name@
  version: @project.version@
  author: Darwin

server:
  port: 9091

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/clientes/**
          filters:
            - StripPrefix=2
        - id: movement-service
          uri: lb://movement-service
          predicates:
            - Path=/api/movimientos/**
          filters:
            - StripPrefix=2
