application:
  title: @project.name@
  version: @project.version@
  author: Darwin

server:
  port: 9090

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 30

  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

  datacenter: Dardan
  environment: Development