application:
  title: @project.name@
  version: @project.version@
  author: Darwin

server:
  port: 8081

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

spring:
  application:
    name: movement-service
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ddqs-devsu-pt.postgres.database.azure.com/ddqs_devsu_pt
    username: postgres
    password: Qwerty*123

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: swagger-ui.html
    enabled: true